/**
 * Generates src/data.ts from backend/seed_data.json so the app's offline seed and
 * the database seed can never drift. Run: npm run gen:seed
 */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const seed = JSON.parse(fs.readFileSync(path.join(root, 'backend/seed_data.json'), 'utf8'));

const items = seed.items.map((i) => ({
  id: i.id,
  city: i.city,
  title: i.title,
  hood: i.hood,
  category: i.category,
  durationMin: i.duration_min,
  price: i.price,
  bestTime: i.best_time,
  note: i.note,
  tip: i.tip,
  tags: i.tags,
  img: i.img,
  photo: null,
  photoThumb: null,
  photoCredit: null,
  photoLicense: null,
  photoSource: null,
  photoProvider: null,
  wikipedia: null,
}));

const out = `/**
 * GENERATED by scripts/gen-seed.mjs from backend/seed_data.json — do not edit.
 *
 * The hand-written core of the catalogue, and the offline fallback when the API
 * is unreachable. The live catalogue — including the ~100 places per city
 * imported from Wikipedia — lives in MongoDB.
 */
import { CATEGORIES, Tier } from './theme';

export type CityKey = ${Object.keys(seed.cities).map((c) => `'${c}'`).join(' | ')};
export type Category = (typeof CATEGORIES)[number];

export type Item = {
  id: number;
  city: CityKey;
  title: string;
  hood: string;
  category: Category;
  durationMin: number;
  /** 0 free … 3 expensive */
  price: number;
  bestTime: string;
  note: string;
  tip: string;
  tags: string[];
  img: string;
  /** Openly-licensed photo resolved by the API; null in the offline seed. */
  photo: string | null;
  photoThumb: string | null;
  photoCredit: string | null;
  photoLicense: string | null;
  photoSource: string | null;
  photoProvider: string | null;
  wikipedia: string | null;
  /** Your ranking of this, once the API has told us. Never baked into the seed. */
  tier: Tier | null;
  score: number | null;
};

export const CITIES: Record<CityKey, string> = ${JSON.stringify(seed.cities, null, 2)};

/** Every city, in the order the app shows them. */
export const CITY_KEYS = Object.keys(CITIES) as CityKey[];

/** Nothing here is ranked: scores belong to a person, and people live in the database. */
const CURATED = ${JSON.stringify(items, null, 2)};

export const ITEMS: Item[] = CURATED.map((i) => ({ ...i, tier: null, score: null } as Item));

export const itemById = (id: number) => ITEMS.find((i) => i.id === id)!;

/** "Mission · Food · 30m · $$" — the one-line summary used across the app. */
export function meta(item: Pick<Item, 'hood' | 'category' | 'durationMin' | 'price'>) {
  const dur = item.durationMin >= 60
    ? item.durationMin % 60 === 0
      ? \`\${item.durationMin / 60}h\`
      : \`\${Math.floor(item.durationMin / 60)}h \${item.durationMin % 60}m\`
    : \`\${item.durationMin}m\`;
  const price = item.price === 0 ? 'free' : '$'.repeat(item.price);
  return \`\${item.hood} · \${item.category} · \${dur} · \${price}\`;
}
`;

fs.writeFileSync(path.join(root, 'src/data.ts'), out);
console.log(`src/data.ts: ${items.length} curated items`);
