/**
 * Generates src/data.ts from backend/seed_data.json so the app's offline seed and
 * the database seed can never drift. Run: npm run gen:seed
 */
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const seed = JSON.parse(fs.readFileSync(path.join(root, 'backend/seed_data.json'), 'utf8'));

const items = seed.items.map((i) => ({
  id: i.id,
  city: i.city,
  title: i.title,
  hood: i.hood,
  category: i.category,
  durationMin: i.duration_min,
  price: i.price,
  bestTime: i.best_time,
  note: i.note,
  tip: i.tip,
  tags: i.tags,
  img: i.img,
  tier: i.seed_tier ?? null,
  score: i.seed_score ?? null,
}));

const feed = seed.feed.map((p, idx) => ({
  id: `post-${idx}`,
  friend: seed.friends[p.friend],
  itemId: p.item_id,
  score: p.score,
  action: p.action,
  time: p.time,
  likes: p.likes,
  comments: p.comments,
  note: p.note,
  img: p.img,
}));

const out = `/**
 * GENERATED by scripts/gen-seed.mjs from backend/seed_data.json — do not edit.
 *
 * This is the offline fallback: what the app shows when the API is unreachable.
 * The live catalogue comes from MongoDB.
 */
import { Tier } from './theme';

export type CityKey = 'sf' | 'nyc';
export type Category = ${seed.categories.map((c) => `'${c}'`).join(' | ')};

export type Item = {
  id: number;
  city: CityKey;
  title: string;
  hood: string;
  category: Category;
  durationMin: number;
  /** 0 free … 3 expensive */
  price: number;
  bestTime: string;
  note: string;
  tip: string;
  tags: string[];
  img: string;
  tier: Tier | null;
  score: number | null;
};

export type Friend = { name: string; initials: string; color: string };

export const CITIES: Record<CityKey, string> = ${JSON.stringify(seed.cities, null, 2)};

export const CATEGORIES: Category[] = ${JSON.stringify(seed.categories)};

export const FRIENDS: Friend[] = ${JSON.stringify(seed.friends, null, 2)};

export const ITEMS: Item[] = ${JSON.stringify(items, null, 2)};

export type FeedPost = {
  id: string;
  friend: Friend;
  itemId: number;
  score: number;
  action: string;
  time: string;
  likes: number;
  comments: number;
  note: string;
  img: string;
};

export const FEED: FeedPost[] = ${JSON.stringify(feed, null, 2)};

export const itemById = (id: number) => ITEMS.find((i) => i.id === id)!;

/** "Mission · Food · 30m · $$" — the one-line summary used across the app. */
export function meta(item: Pick<Item, 'hood' | 'category' | 'durationMin' | 'price'>) {
  const dur = item.durationMin >= 60
    ? item.durationMin % 60 === 0
      ? \`\${item.durationMin / 60}h\`
      : \`\${Math.floor(item.durationMin / 60)}h \${item.durationMin % 60}m\`
    : \`\${item.durationMin}m\`;
  const price = item.price === 0 ? 'free' : '$'.repeat(item.price);
  return \`\${item.hood} · \${item.category} · \${dur} · \${price}\`;
}
`;

fs.writeFileSync(path.join(root, 'src/data.ts'), out);
console.log(`src/data.ts: ${items.length} items, ${feed.length} feed posts`);
