/**
 * GENERATED by scripts/gen-seed.mjs from backend/seed_data.json — do not edit.
 *
 * The hand-written core of the catalogue, and the offline fallback when the API
 * is unreachable. The live catalogue — including the ~100 places per city
 * imported from Wikipedia — lives in MongoDB.
 */
import { CATEGORIES, Tier } from './theme';

export type CityKey = 'sf' | 'nyc';
export type Category = (typeof CATEGORIES)[number];

export type Item = {
  id: number;
  city: CityKey;
  title: string;
  hood: string;
  category: Category;
  durationMin: number;
  /** 0 free … 3 expensive */
  price: number;
  bestTime: string;
  note: string;
  tip: string;
  tags: string[];
  img: string;
  /** Openly-licensed photo resolved by the API; null in the offline seed. */
  photo: string | null;
  photoThumb: string | null;
  photoCredit: string | null;
  photoLicense: string | null;
  photoSource: string | null;
  wikipedia: string | null;
  /** Your ranking of this, once the API has told us. Never baked into the seed. */
  tier: Tier | null;
  score: number | null;
};

export const CITIES: Record<CityKey, string> = {
  "sf": "San Francisco",
  "nyc": "New York"
};

/** Nothing here is ranked: scores belong to a person, and people live in the database. */
const CURATED = [
  {
    "id": 1,
    "city": "sf",
    "title": "Sutro Baths ruins at sunset",
    "hood": "Outer Richmond",
    "category": "Outdoors",
    "durationMin": 60,
    "price": 0,
    "bestTime": "An hour before sunset",
    "note": "Concrete bones of a Victorian swimming palace, half-flooded, right where the land quits. Climb down into the ruins and stay for the light.",
    "tip": "Check the tide chart — low tide opens the cave at the north end.",
    "tags": [
      "free",
      "sunset",
      "walk"
    ],
    "img": "photo: the ruins",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 4,
    "city": "sf",
    "title": "The Dolores Park slope on a clear day",
    "hood": "Mission",
    "category": "Outdoors",
    "durationMin": 120,
    "price": 0,
    "bestTime": "2pm, sunny",
    "note": "The whole city arranged on a hillside with the skyline in front of it. Bring a blanket, buy something from whoever walks by.",
    "tip": "Upper slope for sun, lower field for shade. The fog decides your evening around 5.",
    "tags": [
      "free",
      "picnic",
      "sunny"
    ],
    "img": "photo: the slope",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 7,
    "city": "sf",
    "title": "Hang gliders at Fort Funston",
    "hood": "Lakeshore",
    "category": "Outdoors",
    "durationMin": 60,
    "price": 0,
    "bestTime": "Windy afternoons",
    "note": "A cliff, a permanent onshore wind, gliders launching a few feet over your head, and more dogs than people. Strange and completely free.",
    "tip": "Windy even in September — bring a layer. The sand ladder down to the beach is steep.",
    "tags": [
      "free",
      "dogs",
      "weird"
    ],
    "img": "photo: a glider",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 8,
    "city": "sf",
    "title": "The bison paddock in Golden Gate Park",
    "hood": "Golden Gate Park",
    "category": "Outdoors",
    "durationMin": 20,
    "price": 0,
    "bestTime": "Late morning",
    "note": "There is a herd of American bison in the middle of the park and nobody believes you until they are standing in front of it.",
    "tip": "Bike it — JFK Drive is car-free. Keep going west to the windmill and Ocean Beach.",
    "tags": [
      "free",
      "weird",
      "bike"
    ],
    "img": "photo: bison",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 12,
    "city": "sf",
    "title": "Riding the Powell-Hyde cable car",
    "hood": "Nob Hill",
    "category": "Landmark",
    "durationMin": 30,
    "price": 1,
    "bestTime": "Early, before the queue",
    "note": "Touristy, expensive per minute, and still the best thing on rails in America if you stand on the running board going down Hyde.",
    "tip": "Board at a mid-route stop instead of the turnaround and skip the hour-long line.",
    "tags": [
      "classic",
      "views",
      "touristy"
    ],
    "img": "photo: the car",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 13,
    "city": "sf",
    "title": "Floor 7 at SFMOMA",
    "hood": "SoMa",
    "category": "Culture",
    "durationMin": 90,
    "price": 2,
    "bestTime": "Thursday evening",
    "note": "Skip the lower floors and go straight up. Media arts, the Agnes Martin room, and a terrace with a living wall that nobody is ever on.",
    "tip": "Do two floors, not seven. Your feet will file a complaint otherwise.",
    "tags": [
      "art",
      "rainy-day",
      "indoors"
    ],
    "img": "photo: the terrace",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 14,
    "city": "sf",
    "title": "Walking the Lands End Coastal Trail",
    "hood": "Outer Richmond",
    "category": "Outdoors",
    "durationMin": 90,
    "price": 0,
    "bestTime": "Morning, before the fog lifts",
    "note": "Cypress tunnels, shipwrecks at low tide, and the bridge appearing through the trees about two thirds of the way along.",
    "tip": "Start at the visitor center and walk east; the labyrinth is worth the detour.",
    "tags": [
      "free",
      "hike",
      "views"
    ],
    "img": "photo: the trail",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 15,
    "city": "nyc",
    "title": "Brooklyn Bridge at dawn",
    "hood": "Dumbo",
    "category": "Landmark",
    "durationMin": 60,
    "price": 0,
    "bestTime": "6am",
    "note": "Start on the Manhattan side at six. The bridge is nearly empty, the skyline lights up behind you, and you are in Dumbo for breakfast before the city wakes.",
    "tip": "Enter at the Centre St stairs. Stay left; the right lane is bikes and they are not joking.",
    "tags": [
      "free",
      "sunrise",
      "walk"
    ],
    "img": "photo: bridge at dawn",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 17,
    "city": "nyc",
    "title": "The Met roof garden",
    "hood": "Upper East Side",
    "category": "Culture",
    "durationMin": 60,
    "price": 3,
    "bestTime": "5pm Friday",
    "note": "One commissioned sculpture a year, a bar nobody needs, and Central Park going gold underneath you while the museum quietly empties out.",
    "tip": "Go straight up when you arrive, then work down. Closed in winter.",
    "tags": [
      "views",
      "art",
      "sunset"
    ],
    "img": "photo: the roof",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 19,
    "city": "nyc",
    "title": "First set at the Village Vanguard",
    "hood": "West Village",
    "category": "Music",
    "durationMin": 90,
    "price": 3,
    "bestTime": "8pm, Monday for the big band",
    "note": "A wedge-shaped basement with perfect sound and eighty years of ghosts in it. Coltrane recorded here. The tables are too small and it does not matter.",
    "tip": "Reserve ahead, arrive 45 minutes early for a decent seat. Cash bar.",
    "tags": [
      "jazz",
      "night",
      "iconic"
    ],
    "img": "photo: the room",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 20,
    "city": "nyc",
    "title": "Staten Island Ferry at sunset",
    "hood": "Financial District",
    "category": "Landmark",
    "durationMin": 60,
    "price": 0,
    "bestTime": "Golden hour",
    "note": "Free, twenty-five minutes each way, and the best view of the harbor and the statue that exists. Ride out, turn around, ride back.",
    "tip": "Right side going out, left side coming back. Stand at the rail on the open deck.",
    "tags": [
      "free",
      "views",
      "sunset"
    ],
    "img": "photo: the harbor",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 21,
    "city": "nyc",
    "title": "Late show at the Comedy Cellar",
    "hood": "Greenwich Village",
    "category": "Culture",
    "durationMin": 90,
    "price": 2,
    "bestTime": "11:30pm",
    "note": "A low brick basement where famous people drop in unannounced to work out material on eighty strangers. The 11:30 is the one worth booking.",
    "tip": "Two-drink minimum, and dinner upstairs at the Olive Tree gets you in the door.",
    "tags": [
      "night",
      "comedy",
      "drop-ins"
    ],
    "img": "photo: the cellar sign",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 22,
    "city": "nyc",
    "title": "Getting lost in the Ramble",
    "hood": "Central Park",
    "category": "Outdoors",
    "durationMin": 60,
    "price": 0,
    "bestTime": "Weekday morning",
    "note": "Thirty-six acres of deliberately confusing woodland in the middle of the park. No sightlines, no crowds, actual birds.",
    "tip": "Come out at Bethesda Terrace and sit under the arcade.",
    "tags": [
      "free",
      "quiet",
      "walk"
    ],
    "img": "photo: the woods",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 24,
    "city": "nyc",
    "title": "The Roosevelt Island tram",
    "hood": "Midtown East",
    "category": "Landmark",
    "durationMin": 30,
    "price": 0,
    "bestTime": "Dusk",
    "note": "A commuter cable car that takes a subway swipe and floats you over the East River past the Queensboro Bridge at rooftop height.",
    "tip": "Costs a normal fare. Ride it both ways at dusk and stand at the front.",
    "tags": [
      "cheap",
      "views",
      "underrated"
    ],
    "img": "photo: the tram",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 25,
    "city": "nyc",
    "title": "The third floor of the Strand",
    "hood": "Union Square",
    "category": "Shop",
    "durationMin": 60,
    "price": 1,
    "bestTime": "Rainy afternoon",
    "note": "Eighteen miles of books, and the rare book room upstairs is a quiet wood-panelled break from the scrum downstairs.",
    "tip": "Start on three and work down. Buy one book. One.",
    "tags": [
      "books",
      "rainy-day",
      "indoors"
    ],
    "img": "photo: the stacks",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  },
  {
    "id": 26,
    "city": "nyc",
    "title": "Sitting on the Domino Park steps",
    "hood": "Williamsburg",
    "category": "Outdoors",
    "durationMin": 45,
    "price": 0,
    "bestTime": "Late afternoon",
    "note": "Salvaged syrup tanks, a stretch of waterfront, and the Manhattan skyline doing the thing it does. Tacos from the stand behind you.",
    "tip": "Walk north to the ferry landing and take the boat back instead of the L.",
    "tags": [
      "free",
      "views",
      "waterfront"
    ],
    "img": "photo: the steps",
    "photo": null,
    "photoThumb": null,
    "photoCredit": null,
    "photoLicense": null,
    "photoSource": null,
    "wikipedia": null
  }
];

export const ITEMS: Item[] = CURATED.map((i) => ({ ...i, tier: null, score: null } as Item));

export const itemById = (id: number) => ITEMS.find((i) => i.id === id)!;

/** "Mission · Food · 30m · $$" — the one-line summary used across the app. */
export function meta(item: Pick<Item, 'hood' | 'category' | 'durationMin' | 'price'>) {
  const dur = item.durationMin >= 60
    ? item.durationMin % 60 === 0
      ? `${item.durationMin / 60}h`
      : `${Math.floor(item.durationMin / 60)}h ${item.durationMin % 60}m`
    : `${item.durationMin}m`;
  const price = item.price === 0 ? 'free' : '$'.repeat(item.price);
  return `${item.hood} · ${item.category} · ${dur} · ${price}`;
}
